#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c /home/peter/.config/bspwm/sxhkdrc &

#!/usr/bin/env sh# Terminate already running bar instances
killall -q polybar
killall -q pasystray
# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done
# Launch: 'top' is the name of my Polybar
polybar -c ~/.config/bspwm/pbar_config top &

# start systray apps
nm-applet &
pasystray &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

#sst workspace 6 to master stack
bsp-layout set tall 6 -- --master-size 0.4
bsp-layout set tall 1 -- --master-size 0.4
bsp-layout set tall 2 -- --master-size 0.4
bsp-layout set tall 3 -- --master-size 0.4

bspc config automatic_scheme tall

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config active_border_color "#00FF00"
bspc config focused_border_color "#2F2CC2"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Microsoft-edge-dev desktop='^3' follow=on
bspc rule -a Microsoft-edge desktop='^4' follow=on
bspc rule -a firefox desktop='^5' follow=on

	
# $ bspc config automatic_scheme # prints the current value
# > alternate
# $ bspc config automatic_scheme longest_side
# $ bspc config automatic_scheme alternate
# $ bspc config automatic_scheme spiral
